erDiagram
    tblRole ||--o{ tblRolePermissionJoiner : "RoleId FK"
    tblRole ||--o{ tblUserRoleJoiner : "RoleId FK"
    tblRemovedReservation ||--o{ tblRemovedReservationResources : "ReservationId FK"
    tblRemovedReservation ||--o{ tblRemovedReservationPilots : "ReservationId FK"
    tblRemovedReservation ||--o{ tblRemovedReservationFlightDetails : "ReservationId FK"
    tblAddress ||--o{ tblCompanyAddressJoiner : "AddressId FK"
    tblPlugInModule ||..o{ tblCompanyPlugInModuleJoiner : "PlugInModuleId FK"
    tblCompanyGalleries ||--o{ tblCompanyGalleryImages : "GalleryId FK"
    tblLocations ||--o{ tblLocationToCompanyJoiner : "LocationId FK"
    tblLocations ||--o{ tblLocationToPersonJoiner : "LocationId FK"
    tblEngine ||--o{ tblEnginePropellerJoiner : "EngineId FK"
    tblContactNumbers ||--o{ tblPersonToContactNumberJoiner : "ContactNumberId FK"
    tblReservation ||..o{ FlightAlerts : "ReservationId FK"
    ReservationBatches ||--o{ ReservationBatchReservations : "ReservationBatchId FK"
    tblReservationTypes ||..o{ ReservationTypeToPreflightAuthorizingUsersJoiner : "ReservationTypeId FK"
    tblFlightRecord ||--o{ tblFlightRecordResources : "FlightRecordId FK"
    GlobalUserSettings ||..o{ LogTenUserOperatorJoiner : "UserId FK"
    tblFlightRecord ||--o{ tblMeterRecords : "FlightRecordId FK"
    tblFlightRecord ||--o{ tblStandardFlightRecord : "FlightRecordId FK"
    ScheduleMatchUserPreferences ||..o{ ScheduleMatchUserPreferencesToAircraftJoiner : "PreferenceId FK"
    tblReservation ||--o{ tblReservationPilots : "ReservationId FK"
    tblAircraft ||..o{ ScheduleMatchUserPreferencesToAircraftJoiner : "AircraftId FK"
    tblReservation ||--o{ tblReservationFlightDetails : "ReservationId FK"
    ScheduleMatchUserPreferences ||..o{ ScheduleMatchUserPreferencesToFlightInstructorJoiner : "PreferenceId FK"
    tblReservation ||--o{ tblReservationResources : "ReservationId FK"
    tblReservation ||--o{ tblReservationNotifications : "ReservationId FK"
    tblFlightInstructor ||..o{ ScheduleMatchUserPreferencesToFlightInstructorJoiner : "InstructorId FK"
    ScheduleMatchUserPreferences ||..o{ ScheduleMatchUserPreferencesToSchedulingGroupsJoiner : "PreferenceId FK"
    tblDispatchRecords ||--o{ tblDispatchPilots : "DispatchId FK"
    tblDispatchRecords ||--o{ tblDispatchResources : "DispatchId FK"
    Labels ||--o{ LabelToRoleJoiner : "LabelId FK"
    tblPostItems ||--o{ tblPostItemRoleIds : "PostItemId FK"
    tblRole ||--o{ LabelToRoleJoiner : "RoleId FK"
    Labels ||--o{ LabelToUserJoiner : "LabelId FK"
    LabelCategories ||--o{ Labels : "LabelCategoryId FK"
    tblReservation ||--o{ ReservationTrainingSessions : "ReservationId FK"
    tblLocations ||--o{ LocationToIcaoLocationsJoiner : "LocationId FK"
    tblAddress ||--o{ tblAddressParts : "AddressId FK"
    tblAddress ||--o{ tblPersonAddressJoiner : "AddressId FK"